version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8082:8085"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/team_1_db
      SPRING_DATASOURCE_USERNAME: team_1_user
      SPRING_DATASOURCE_PASSWORD: team_1_pass
    depends_on:
      - postgres
    networks:
      - jenkins-net

  postgres:
    image: postgres:15-alpine
    container_name: team_1_dev_1_postgres
    environment:
      POSTGRES_DB: team_1_db
      POSTGRES_USER: team_1_user
      POSTGRES_PASSWORD: team_1_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jenkins-net

volumes:
  postgres_data:

networks:
  jenkins-net:
    driver: bridge
